### ISSUE TITLE
Ability to control via broadcast intents

### ISSUE THREAD

**Issue by dallasgutauckis** [emmaguy/clean-status-bar#49]
This would enable debug applications as well as adb shell usage to change configuration, especially useful for automation purposes.

If I get some time, I'll work on this this week.

**Comment by mars3142** [comment]
You wanted to start/stop/configure the app with external intents? That's a really cool idea.

**Comment by cypressious** [comment]
Especially useful, if you have automated the screenshot process.

**Comment by cypressious** [comment]
Created PR #63

**Comment by emmaguy** [comment]
Done in v1.1.3 which is now available under Releases - thank you @cypressious!
