### ISSUE TITLE
custom icons (on the left side)

### ISSUE THREAD

**Issue by mars3142** [emmaguy/clean-status-bar#50]
Ability to add custom/external icons

// found in the play store comments

**Comment by emmaguy** [comment]
Unsure if I want this - want the app to be as stock as possible, letting people upload whatever they want doesn't really go along with that

**Comment by mars3142** [comment]
For example... I had an app, that produces notifications. Now I use your app and all my notification icons are gone. How can I fake them? There is no way to do it right now.

**Comment by emmaguy** [comment]
Yeah they should just not use the app :)

**Comment by emmaguy** [comment]
I mean why use an app to hide notifications if you want to show them? That's crazy

**Comment by mars3142** [comment]
Hmm. Okay, that's an argument, where I can't say anything against.
