### ISSUE TITLE
Android M Preview uses 24dp status bar instead of 25dp

### ISSUE THREAD

**Issue by marcardar** [emmaguy/clean-status-bar#51]
Android M Preview uses 24dp status bar instead of 25dp.

Maybe the app already handles this (I'm not sure), but at the very least it's important to check!

**Comment by emmaguy** [comment]
Well spotted! You're right, it probably needs an update - thanks for reporting it :smile:

**Comment by marcardar** [comment]
You're welcome!  Good to see a status bar that's both cleaner and leaner :)

**Comment by emmaguy** [comment]
Just checked on a nexus 6 and it's actually working great as is - I read the status bar height variable from android, seems fine
