### ISSUE TITLE
Change default_colour_choices

### ISSUE THREAD

**Issue by yoavst** [emmaguy/clean-status-bar#59]
Change them to the 700 colors value from Material Design colors.

**Comment by emmaguy** [comment]
700 is a bit much for the UI I think, noone wants to scroll that much. Would have to be sectioned or something

**Comment by SimonMarquis** [comment]
He is referring to the "level 700" of material colors as described here: https://www.google.com/design/spec/style/color.html
It corresponds to darker (more contrasted) colors. Change will be here: https://github.com/emmaguy/clean-status-bar/blob/b5e1b02da258cc8f9a78bccc29f14fc73c223bc6/app/src/main/res/values/arrays.xml#L51

**Comment by emmaguy** [comment]
Ooooh, I see - thanks @SimonMarquis

**Comment by SimonMarquis** [comment]
![before](https://cloud.githubusercontent.com/assets/1921278/9427896/c1c46c20-4994-11e5-924f-62ef9245ff70.png)
![after](https://cloud.githubusercontent.com/assets/1921278/9427897/c1c598ca-4994-11e5-8195-b31e146fae4e.png)

**Comment by SimonMarquis** [comment]
![after](https://cloud.githubusercontent.com/assets/1921278/9427903/e09963a8-4994-11e5-82c7-a46fa6a8d061.png)
![before](https://cloud.githubusercontent.com/assets/1921278/9427902/e097e35c-4994-11e5-9f38-aace7ac59532.png)
