### ISSUE TITLE
Show Icon of featured apps

### ISSUE THREAD

**Issue by SecUpwN** [emmaguy/clean-status-bar#70]
Good morning @emmaguy, huge thanks for your wonderful tool! I would like `Clean Status Bar` to be able to show the app Icon of one or more apps in the notification bar when they are being featured. So maybe you can add a setting where a user can chose one or more apps that are allowed to be displayed?

The reason for my request is our [Android IMSI-Catcher Detector](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) which displays a changing Status Icon.

**Comment by emmaguy** [comment]
Sorry, but this goes against the point of the app. I don't want it to have this feature.
