### ISSUE TITLE
Project Feature - Android O

### ISSUE THREAD

**Issue by gsantner** [emmaguy/clean-status-bar#74]
Hey there, Android O will not allow to draw over system elements/statusbar anymore.  
I Think this will break this nice utility, at least for users >= Android O.  

<https://plus.google.com/+JamesFennJAFFA2157/posts/VdKZ2LnBziS>

**Comment by emmaguy** [comment]
Yes it will - I'm running the O Preview on my phone and had noticed it was broken, which is a shame. We'll see if that behaviour remains for the final release. I suggest you use Demo Mode instead 😄
